# Shopify App Configuration for iPick Price Tracking
# Self-contained OAuth implementation

client_id = "d749d6d47d2fb7ecb66c3630b1a95d2e"
name = "ipickdemo"
application_url = "https://ipick.io"
embedded = true

[build]
# Include configuration on deploy for self-contained app
include_config_on_deploy = true

[auth]
redirect_urls = [
  "https://ipick.io/api/auth",
  "https://ipick.io/api/shopify/oauth/callback",
  "https://ipick.io/business/dashboard",
  "https://ipick.io/business/integrate",
  "https://ipick.io/api/shopify/oauth/connect"
]

[webhooks]
api_version = "2024-10"

# Webhook endpoints for our self-contained implementation
[[webhooks.handlers]]
api_version = "2024-10"
topics = ["orders/create", "orders/updated", "products/update", "customers/update"]
address = "https://ipick.io/api/shopify/webhooks"

# App proxy configuration (if needed for embedded functionality)
[app_proxy]
url = "https://ipick.io"
subpath = "api"
prefix = "apps"
