[build]
  command = "npx prisma generate && npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_OMIT_KEYS = "DATABASE_URL,GEMINI_API_KEY,N8N_WEBHOOK_URL,GADGET_API_KEY"
  NPM_FLAGS = "--production=false"

[functions]
  external_node_modules = ["express", "@netlify/neon", "bcryptjs", "jsonwebtoken", "cors", "helmet", "compression", "cookie-parser", "@react-email/render", "@prisma/client"]
  node_bundler = "esbuild"
  
[[redirects]]
  from = "/api/track-event"
  to = "/.netlify/functions/track-event"
  status = 200

[[redirects]]
  from = "/api/track-shopify-script"
  to = "/.netlify/functions/track-shopify-script"
  status = 200

[[redirects]]
  from = "/api/test-db"
  to = "/.netlify/functions/test-db"
  status = 200

[[redirects]]
  from = "/api/minimal-test"
  to = "/.netlify/functions/minimal-test"
  status = 200

[[redirects]]
  from = "/ref/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/track/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[dev]
  targetPort = 8084
