[build]
  command = "npm run build:netlify && npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_OMIT_KEYS = "DATABASE_URL,GEMINI_API_KEY,N8N_WEBHOOK_URL"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
