# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "16272754ed68cbdcb55e8f579703d92e"
name = "Event Tracking App"
handle = "event-tracking-app-3"
application_url = "https://pavlo4.netlify.app/business/dashboard"
embedded = false

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://pavlo4.netlify.app/api/auth" ]

[pos]
embedded = false
