# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ba93cb813200396568e0cff132da0256"
name = "ipickio"
application_url = "https://checkoutdata.gadget.app/api/shopify/install-or-render"
embedded = true

[build]
include_config_on_deploy = true

[auth]
redirect_urls = [
  "https://checkoutdata.gadget.app/api/connections/auth/shopify/callback"
]

[access_scopes]
scopes = "read_orders"

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = ["checkouts/create"]
  uri = "https://checkoutdata.gadget.app/api/webhooks/shopify/checkouts/create"

  [[webhooks.subscriptions]]
  topics = ["checkouts/update"]
  uri = "https://checkoutdata.gadget.app/api/webhooks/shopify/checkouts/update"

  [[webhooks.subscriptions]]
  topics = ["orders/create"]
  uri = "https://checkoutdata.gadget.app/api/webhooks/shopify/orders/create"
